### ISSUE TITLE
dbuild doesn't work with Java 9

### ISSUE THREAD

**Issue by gkossakowski** [lightbend/dbuild#155]
When trying to run dbuild 0.9.3-SNAPSHOT it blows up with:

```
[specs2] Caused by: scala.tools.scalap.scalax.rules.ScalaSigParserError: Unexpected error: Not a valid class file
[specs2]    at scala.tools.scalap.scalax.rules.Rules$$anonfun$expect$1.apply(Rules.scala:69)
[specs2]    at scala.tools.scalap.scalax.rules.scalasig.ClassFileParser$.parse(ClassFileParser.scala:99)
[specs2]    at scala.tools.scalap.scalax.rules.scalasig.ScalaSigParser$.parse(ScalaSig.scala:50)
[specs2]    at com.lambdaworks.jacks.ScalaTypeSig$.apply(module.scala:267)
[specs2]    at com.lambdaworks.jacks.ScalaSerializers.findSerializer(module.scala:136)
[specs2]    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:179)
[specs2]    at com.fasterxml.jackson.databind.ser.SerializerFactory.createSerializer(SerializerFactory.java:53)
[specs2]    at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:935)
[specs2]    at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:892)
[specs2]    at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:429)
[specs2]    at com.lambdaworks.jacks.IterableSerializer$$anonfun$serialize$1.apply(iterable.scala:26)
[specs2]    at com.lambdaworks.jacks.IterableSerializer$$anonfun$serialize$1.apply(iterable.scala:21)
[specs2]    at scala.collection.immutable.List.foreach(List.scala:318)
[specs2]    at com.lambdaworks.jacks.IterableSerializer.serialize(iterable.scala:21)
[specs2]    at com.lambdaworks.jacks.IterableSerializer.serialize(iterable.scala:14)
[specs2]    at com.lambdaworks.jacks.CaseClassSerializer.serialize(case.scala:17)
[specs2]    at com.lambdaworks.jacks.CaseClassSerializer.serialize(case.scala:13)
[specs2]    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:224)
[specs2]    at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:612)
[specs2]    at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:530)
[specs2]    at com.lambdaworks.jacks.JacksMapper.writeValueAsString(jacks.scala:24)
[specs2]    at com.typesafe.dbuild.model.Utils$$anonfun$writeValue$1.apply(Utils.scala:46)
[specs2]    at com.typesafe.dbuild.model.Utils$$anonfun$writeValue$1.apply(Utils.scala:46)
[specs2]    at com.typesafe.dbuild.model.ClassLoaderMadness$.withContextLoader(ClassLoaderMadness.scala:8)
[specs2]    at com.typesafe.dbuild.model.Utils$.writeValue(Utils.scala:46)
[specs2]    at com.typesafe.dbuild.plugin.DBuildRunner$.printResults(DBuildRunner.scala:88)
```

The underlying reason seems to be lack of support for Java 9 class file format in scalap that dbuild is using transitively.

**Comment by SethTisue** [comment]
umbrella ticket on JDK 9 support for Scala is https://github.com/scala/scala-dev/issues/139

**Comment by SethTisue** [comment]
I'm delighted to report that dbuild seems to work fine on Java 9 with sbt 0.13.16 as long as you first run the sbt launcher to copy rt.jar to a directory under `~/.sbt/0.13` and then do e.g. `extra.options: ["-Dscala.ext.dirs=/Users/tisue/.sbt/0.13/java9-rt-ext-oracle_corporation_9"]` so that Scala 2.10 can find it (see https://github.com/sbt/sbt-launcher-package/pull/143 for details/background)

**Comment by SethTisue** [comment]
this is working fine now (in the context of https://github.com/scala/community-builds/issues/609)
