### ISSUE TITLE
unexpected missing dependency (pom-only?)

### ISSUE THREAD

**Issue by adriaanm** [lightbend/dbuild#173]
Given

```
[specs2] [info] :: delivering :: org.specs2#specs2;3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66 :: 3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66 :: release :: Thu Jul 09 23:40:34 UTC 2015
[specs2] [info]     delivering ivy file to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/target/scala-2.12.0-dbuildxefbf1b4136d6e576f708105a537fcd7f94e5b667/ivy-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.xml
[specs2] --== End Building specs2 ==--
...
[scalamock] Retrieved from project specs2 (commit: c0ca283a5f551be6fbf1e71eeac55d0e7db156ce): 52 artifacts
```

I was not expecting to see

```
[scalamock] [error] **** Missing dependency: the library org.specs2#specs2 is not provided (in space "default") by any project in this configuration file.
```

Is it suspicious there's only a "delivering ivy file" line for specs2 and no "publish committed"?

Here's a more complete excerpt from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/39/console:

```
[specs2] [info] Wrote /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/tests/target/scala-2.12.0-dbuildxefbf1b4136d6e576f708105a537fcd7f94e5b667/specs2-tests-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.pom
[specs2] [info] :: delivering :: org.specs2#specs2-tests;3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66 :: 3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66 :: release :: Thu Jul 09 23:40:31 UTC 2015
[specs2] [info]     delivering ivy file to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/tests/target/scala-2.12.0-dbuildxefbf1b4136d6e576f708105a537fcd7f94e5b667/ivy-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.xml
[specs2] [info]     published specs2-tests to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/.dbuild/local-publish-repo/org/specs2/specs2-tests/3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.part/specs2-tests-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.pom
[specs2] [info]     published specs2-tests to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/.dbuild/local-publish-repo/org/specs2/specs2-tests/3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.part/specs2-tests-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.jar
[specs2] [info]     published specs2-tests to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/.dbuild/local-publish-repo/org/specs2/specs2-tests/3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.part/specs2-tests-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66-sources.jar
[specs2] [info]     published specs2-tests to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/.dbuild/local-publish-repo/org/specs2/specs2-tests/3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.part/specs2-tests-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66-javadoc.jar
[specs2] [info]     publish commited: moved /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/.dbuild/local-publish-repo/org/specs2/specs2-tests/3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.part 
[specs2] [info]         to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/.dbuild/local-publish-repo/org/specs2/specs2-tests/3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66
[specs2] ----------------------
[specs2] Processing subproject: specs2
[specs2] All Dependencies for subproject specs2:
...
[specs2] Running build: specs2
[specs2] Publishing: specs2
[specs2] [warn] Credentials file /home/jenkins/.sbt/specs2.credentials does not exist
[specs2] [info] Updating {file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/}specs2...
[specs2] [info] Done updating.
[specs2] [info] :: delivering :: org.specs2#specs2;3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66 :: 3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66 :: release :: Thu Jul 09 23:40:34 UTC 2015
[specs2] [info]     delivering ivy file to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-d99fea3242daf9bc909fd943a0e63524603b4c66/target/scala-2.12.0-dbuildxefbf1b4136d6e576f708105a537fcd7f94e5b667/ivy-3.6.1-20150709232923-c0ca283-dbuildxd99fea3242daf9bc909fd943a0e63524603b4c66.xml
[specs2] --== End Building specs2 ==--
[scalamock] --== Building scalamock ==--
[scalamock] Resolving: https://github.com/adriaanm/scalamock.git#54b5b8981b813c44acb5bf4218104ec9ffbc9ab9 in directory: ./target-0.9.1/project-builds/scalamock-e62fbaba0e08aa20d91ffb2208ed2968e9902a83
...
[scalamock] Retrieved from project specs2 (commit: c0ca283a5f551be6fbf1e71eeac55d0e7db156ce): 52 artifacts
[scalamock] Written RepeatableProjectBuild metadata: meta/project/e62fbaba0e08aa20d91ffb2208ed2968e9902a83
[scalamock] Using sbt version: 0.13.8
...
[scalamock] Processing subproject: specs2
[scalamock] [error] **** Missing dependency: the library org.specs2#specs2 is not provided (in space "default") by any project in this configuration file.
[scalamock] [error] In order to control which version is used, please add the corresponding project to the build file
[scalamock] [error] (or use "check-missing:false" to ignore (not recommended)).
[scalamock] java.lang.RuntimeException: Required dependency not found
[scalamock]     at scala.sys.package$.error(package.scala:27)
[scalamock]     at com.typesafe.dbuild.DistributedRunner$$anonfun$fixModule$2.apply(DistributedRunner.scala:179)
[scalamock]     at com.typesafe.dbuild.DistributedRunner$$anonfun$fixModule$2.apply(DistributedRunner.scala:154)
[scalamock]     at scala.Option.getOrElse(Option.scala:120)
[scalamock]     at com.typesafe.dbuild.DistributedRunner$.fixModule(DistributedRunner.scala:154)
[scalamock]     at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23$$anonfun$apply$24.apply(DistributedRunner.scala:352)
[scalamock]     at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23$$anonfun$apply$24.apply(DistributedRunner.scala:352)
[scalamock]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[scalamock]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[scalamock]     at scala.collection.immutable.List.foreach(List.scala:318)
[scalamock]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[scalamock]     at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[scalamock]     at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23.apply(DistributedRunner.scala:352)
[scalamock]     at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23.apply(DistributedRunner.scala:351)
[scalamock]     at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
[scalamock]     at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
[scalamock]     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[scalamock]     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[scalamock]     at sbt.std.Transform$$anon$4.work(System.scala:63)
[scalamock]     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[scalamock]     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[scalamock]     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[scalamock]     at sbt.Execute.work(Execute.scala:235)
[scalamock]     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[scalamock]     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[scalamock]     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[scalamock]     at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[scalamock]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[scalamock]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[scalamock]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[scalamock]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[scalamock]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[scalamock]     at java.lang.Thread.run(Thread.java:745)
[scalamock] [error] (specs2/*:allDependencies) Required dependency not found
[scalamock:error] Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/scalamock-e62fbaba0e08aa20d91ffb2208ed2968e9902a83/,specs2)),Global,Global,Global),allDependencies)), tpe=Error, msg=None, causes=List(), directCause=Some(java.lang.RuntimeException: Required dependency not found))
[scalamock:error]   at sbt.Incomplete.copy(Incomplete.scala:17)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$taskToKey$1.apply(EvaluateTask.scala:383)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$taskToKey$1.apply(EvaluateTask.scala:382)
[scalamock:error]   at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[scalamock:error]   at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[scalamock:error]   at sbt.Incomplete$$anonfun$sbt$Incomplete$$visit$1$1.apply(Incomplete.scala:32)
[scalamock:error]   at sbt.Incomplete$$anonfun$sbt$Incomplete$$visit$1$1.apply(Incomplete.scala:32)
[scalamock:error]   at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
[scalamock:error]   at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
[scalamock:error]   at sbt.Incomplete$.sbt$Incomplete$$visit$1(Incomplete.scala:32)
[scalamock:error]   at sbt.Incomplete$.transform(Incomplete.scala:36)
[scalamock:error]   at sbt.Incomplete$.transformBU(Incomplete.scala:26)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$transformInc$1.apply(EvaluateTask.scala:381)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$transformInc$1.apply(EvaluateTask.scala:381)
[scalamock:error]   at scala.util.Either$LeftProjection.map(Either.scala:377)
[scalamock:error]   at sbt.EvaluateTask$.transformInc(EvaluateTask.scala:381)
[scalamock:error]   at sbt.EvaluateTask$.run$1(EvaluateTask.scala:347)
[scalamock:error]   at sbt.EvaluateTask$.runTask(EvaluateTask.scala:361)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:258)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:258)
[scalamock:error]   at scala.Option$WithFilter.map(Option.scala:206)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:258)
[scalamock:error]   at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:257)
[scalamock:error]   at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:293)
[scalamock:error]   at sbt.EvaluateTask$.apply(EvaluateTask.scala:257)
[scalamock:error]   at sbt.EvaluateTask$.apply(EvaluateTask.scala:255)
[scalamock:error]   at sbt.Extracted.runTask(Extracted.scala:43)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$.com$typesafe$dbuild$DistributedRunner$$buildTestPublish$1(DistributedRunner.scala:584)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$19.apply(DistributedRunner.scala:616)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$19.apply(DistributedRunner.scala:616)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$runAggregate$1.apply(DistributedRunner.scala:70)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$runAggregate$1.apply(DistributedRunner.scala:67)
[scalamock:error]   at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
[scalamock:error]   at scala.collection.immutable.List.foldLeft(List.scala:84)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$.com$typesafe$dbuild$DistributedRunner$$runAggregate(DistributedRunner.scala:67)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$14.apply(DistributedRunner.scala:574)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$14.apply(DistributedRunner.scala:574)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$.buildStuff(DistributedRunner.scala:616)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$generateArtifacts$1.apply(DistributedRunner.scala:745)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$generateArtifacts$1.apply(DistributedRunner.scala:745)
[scalamock:error]   at com.typesafe.dbuild.StateHelpers$.saveLastMsg(StateHelpers.scala:35)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$.generateArtifacts(DistributedRunner.scala:745)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$buildIt$1.apply(DistributedRunner.scala:749)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$buildIt$1.apply(DistributedRunner.scala:749)
[scalamock:error]   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
[scalamock:error]   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
[scalamock:error]   at sbt.Command$.process(Command.scala:92)
[scalamock:error]   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[scalamock:error]   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[scalamock:error]   at sbt.State$$anon$1.process(State.scala:184)
[scalamock:error]   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[scalamock:error]   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[scalamock:error]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[scalamock:error]   at sbt.MainLoop$.next(MainLoop.scala:98)
[scalamock:error]   at sbt.MainLoop$.run(MainLoop.scala:91)
[scalamock:error]   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
[scalamock:error]   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
[scalamock:error]   at sbt.Using.apply(Using.scala:24)
[scalamock:error]   at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
[scalamock:error]   at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
[scalamock:error]   at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
[scalamock:error]   at sbt.MainLoop$.runLogged(MainLoop.scala:24)
[scalamock:error]   at sbt.StandardMain$.runManaged(Main.scala:53)
[scalamock:error]   at sbt.xMain.run(Main.scala:28)
[scalamock:error]   at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
[scalamock:error]   at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
[scalamock:error]   at xsbt.boot.Launch$.run(Launch.scala:57)
[scalamock:error]   at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
[scalamock:error]   at xsbt.boot.Launch$.launch(Launch.scala:65)
[scalamock:error]   at xsbt.boot.Launch$.apply(Launch.scala:16)
[scalamock:error]   at xsbt.boot.Boot$.runImpl(Boot.scala:32)
[scalamock:error]   at xsbt.boot.Boot$.main(Boot.scala:21)
[scalamock:error]   at xsbt.boot.Boot.main(Boot.scala)
[scalamock:error] Caused by: java.lang.RuntimeException: Required dependency not found
[scalamock:error]   at scala.sys.package$.error(package.scala:27)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$fixModule$2.apply(DistributedRunner.scala:179)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$fixModule$2.apply(DistributedRunner.scala:154)
[scalamock:error]   at scala.Option.getOrElse(Option.scala:120)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$.fixModule(DistributedRunner.scala:154)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23$$anonfun$apply$24.apply(DistributedRunner.scala:352)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23$$anonfun$apply$24.apply(DistributedRunner.scala:352)
[scalamock:error]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[scalamock:error]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[scalamock:error]   at scala.collection.immutable.List.foreach(List.scala:318)
[scalamock:error]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[scalamock:error]   at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23.apply(DistributedRunner.scala:352)
[scalamock:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$fixDependencies2$1$$anonfun$apply$23.apply(DistributedRunner.scala:351)
[scalamock:error]   at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
[scalamock:error]   at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
[scalamock:error]   at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[scalamock:error]   at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[scalamock:error]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[scalamock:error]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[scalamock:error]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[scalamock:error]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[scalamock:error]   at sbt.Execute.work(Execute.scala:235)
[scalamock:error]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[scalamock:error]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[scalamock:error]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[scalamock:error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[scalamock:error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[scalamock:error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[scalamock:error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[scalamock:error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[scalamock:error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[scalamock:error]   at java.lang.Thread.run(Thread.java:745)
[scalamock:error] java.lang.RuntimeException: Required dependency not found
[scalamock:error]   at scala.sys.package$.error(package.scala:27)
[scalamock:error]   at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[scalamock:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scalamock:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scalamock:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[scalamock:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[scalamock:error]   at sbt.IO$.withTemporaryFile(IO.scala:311)
[scalamock:error]   at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[scalamock:error]   at distributed.support.sbt.SbtBuilder$.buildSbtProject(SbtBuildRunner.scala:84)
[scalamock:error]   at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:68)
[scalamock:error]   at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:18)
[scalamock] --== End Building scalamock ==--
```

**Comment by adriaanm** [comment]
Worked around by https://github.com/adriaanm/specs2/commit/cad1e1ad1b8e034fb1119fae47d81c9239366c86

```
[specs2] [info] :: delivering :: org.specs2#specs2;3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e :: 3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e :: release :: Fri Jul 10 00:42:33 UTC 2015
[specs2] [info] 	delivering ivy file to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-208a55f57f92fdbdbd8cbce59e755511ef48433e/target/scala-2.12.0-dbuildxefbf1b4136d6e576f708105a537fcd7f94e5b667/ivy-3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.xml
[specs2] [info] 	published specs2 to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-208a55f57f92fdbdbd8cbce59e755511ef48433e/.dbuild/local-publish-repo/org/specs2/specs2/3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.part/specs2-3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.pom
[specs2] [info] 	published specs2 to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-208a55f57f92fdbdbd8cbce59e755511ef48433e/.dbuild/local-publish-repo/org/specs2/specs2/3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.part/specs2-3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.jar
[specs2] [info] 	published specs2 to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-208a55f57f92fdbdbd8cbce59e755511ef48433e/.dbuild/local-publish-repo/org/specs2/specs2/3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.part/specs2-3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e-sources.jar
[specs2] [info] 	published specs2 to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-208a55f57f92fdbdbd8cbce59e755511ef48433e/.dbuild/local-publish-repo/org/specs2/specs2/3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.part/specs2-3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e-javadoc.jar
[specs2] [info] 	publish commited: moved /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-208a55f57f92fdbdbd8cbce59e755511ef48433e/.dbuild/local-publish-repo/org/specs2/specs2/3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e.part 
[specs2] [info] 		to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-208a55f57f92fdbdbd8cbce59e755511ef48433e/.dbuild/local-publish-repo/org/specs2/specs2/3.6.1-20150710002820-cad1e1a-dbuildx208a55f57f92fdbdbd8cbce59e755511ef48433e
```

**Comment by SethTisue** [comment]
there may not be any actual dbuild issue here. these days dependencies are supposed to depend on specs2-core, not plain specs2

**Comment by cunei** [comment]
It seems this was just an old specs2 quirk, so closing.
