### ISSUE TITLE
sbt 1.2.1 support

### ISSUE THREAD

**Issue by SethTisue** [lightbend/dbuild#215]
looks like another update is needed for 1.2.1?

```
[twotails] [error] scala.ScalaReflectionException: value reapply encapsulates multiple overloaded alternatives and cannot be treated as a method. Consider invoking `<offending symbol>.asTerm.alternatives` and manually picking the required method
[twotails] [error] 	at scala.reflect.api.Symbols$SymbolApi.asMethod(Symbols.scala:228)
[twotails] [error] 	at scala.reflect.api.Symbols$SymbolApi.asMethod$(Symbols.scala:222)
[twotails] [error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:94)
[twotails] [error] 	at com.typesafe.dbuild.adapter.Adapter$.reapplySettings(Adapter.scala:77)
[twotails] [error] 	at com.typesafe.dbuild.plugin.DBuildRunner$.newState(DBuildRunner.scala:737)
[twotails] [error] 	at com.typesafe.dbuild.plugin.DependencyAnalysis$.printCmd(DependencyAnalysis.scala:299)
[twotails] [error] 	at $daa84e8a87748447d9ce$.$anonfun$$sbtdef$2(/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.13/extraction/38f6b43e0ada1518cdbc47ff40da89e9546c6c98/projects/c56341d41dd619863997f409b00d38600b7bcfb3/project/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1)
[twotails] [error] 	at scala.Function1.$anonfun$an
```

seen at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3270/console after scala/community-builds@5a49f7d3765c9252face5eac18e50c60ac09165b

/cc @eed3si9n

**Comment by eed3si9n** [comment]
Ref https://github.com/sbt/sbt/pull/4302

**Comment by cunei** [comment]
I'm on it

**Comment by cunei** [comment]
0.9.14 is out

**Comment by SethTisue** [comment]
scala/community-builds@c719c3858d8055cf6aa791df1c6b3ae001846694

thanks Toni!
